config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'root#index'
  resources :exchanges, only: %i[index create show] do
    resources :markets, only: %i[index create show update] do
      resources :orders, only: %i[create]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exchange.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: exchanges
#
#  id              :integer          not null, primary key
#  code            :string(255)      not null
#  name            :string(255)
#  fee             :decimal(15, 10)
#  trade_enabled   :boolean
#  balance_enabled :boolean
#  url             :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_exchanges_on_code  (code)
#

class Exchange < ApplicationRecord
  has_many :markets

  def self.from_json(json)
    Exchange.new(
      code: json[:exch_code],
      name: json[:exch_name],
      fee: BigDecimal.new(json[:exch_fee]),
      trade_enabled: json[:exch_trade_enabled]&.to_i == 1,
      balance_enabled: json[:exch_balance_enabled]&.to_i == 1,
      url: json[:exch_url]
    )
  end
end

app/models/market.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: markets
#
#  id          :integer          not null, primary key
#  exchange_id :integer          not null
#  code        :string(255)      not null
#  subscribed  :boolean          default(FALSE), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_markets_on_exchange_id_and_code  (exchange_id,code)
#  index_markets_on_subscribed            (subscribed)
#

class Market < ApplicationRecord
  belongs_to :exchange
  has_many :orders

  def self.from_json(exchange, json)
    m = Market.new
    m.exchange = exchange
    m.code = json[:mkt_name]
    m
  end

  def as_json(arg)
    json = super
    json[:subscription_code] = "ORDER-#{exchange.code}--#{code.gsub('/', '--')}"
    json
  end
end

app/models/order.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: orders
#
#  id                 :integer          not null, primary key
#  market_id          :integer          not null
#  uuid               :string(255)      not null
#  external_order_id  :string(255)
#  status             :integer          not null
#  time_in_force      :integer          not null
#  side               :integer          not null
#  price_type         :integer          not null
#  price              :decimal(15, 10)  not null
#  quantity           :decimal(15, 10)  not null
#  remaining_quantity :decimal(15, 10)  not null
#  error_message      :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
# Indexes
#
#  index_orders_on_external_order_id     (external_order_id)
#  index_orders_on_market_id_and_status  (market_id,status)
#  index_orders_on_uuid                  (uuid) UNIQUE
#

class Order < ApplicationRecord
  belongs_to :market
  before_create :init_params

  # end_states: [executed, cancelled, rejected, expired]
  enum status: {
    requested:        10,
    pending:          11,
    executed:         12,
    rejected:         13,
    expired:          14,
    requested_cancel: 40,
    pending_cancel:   41,
    cancelled:        42,
    error:            99
  }

  enum time_in_force: {
    good_till_cancel: 1,
    immediate_or_cancel: 2
  }

  enum side: {
    buy: 1,
    sell: 2
  }

  enum price_type: {
    limit_order: 3,
    stop_limit_order: 6,
    limit_margin_order: 8,
    stop_limit_margin_order: 9
  }

  scope :open_orders, -> { where(status: %i[requested pending requested_cancel pending_cancel]) }
  
  def status
    self[:status]&.to_sym
  end

  def time_in_force
    self[:time_in_force]&.to_sym
  end

  def side
    self[:side]&.to_sym
  end

  def price_type
    self[:price_type]&.to_sym
  end

  private

  def init_params
    self[:uuid] ||= SecureRandom.uuid
    self[:status] ||= :requested
    self[:remaining_quantity] ||= quantity
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true

  class Forbidden < ActionController::ActionControllerError; end

  rescue_from WeakParameters::ValidationError do |e|
    logger.error e
    render json: { message: e.message }, status: 400
  end

  rescue_from ActiveRecord::RecordNotFound do |e|
    logger.error e
    head 404
  end

  rescue_from Forbidden do |e|
    @exception = e
    render 'errors/forbidden', status: 403
  end

  def not_found
    raise ActiveRecord::RecordNotFound
  end

  def forbidden
    raise Forbidden
  end

  def bad_request(e, status = 400)
    render status: status, json: { status: 'error', message: (e.is_a?(String) ? e : e.message) }.to_json
  end

  def after_sign_out_path_for(_resource)
    root_path
  end

  private

  def set_raven_context
    Raven.user_context(session_id: request.cookies['raksul'])
    Raven.extra_context(params: params.to_h, url: request.url)
  end
end

app/controllers/exchanges_controller.rb
# frozen_string_literal: true

class ExchangesController < ApplicationController
  def index
    @exchanges = Exchange.all
  end

  def create
    @exchanges = CoinigyService.new.refresh_exchanges
    redirect_to exchanges_path
  end

  def show
    not_found if exchange.nil?
  end

  private

  def exchange
    @exchange ||= Exchange.includes(:markets).find_by(code: params[:id])
  end
end

app/controllers/markets_controller.rb
# frozen_string_literal: true

class MarketsController < ApplicationController
  def create
    CoinigyService.new.refresh_markets(exchange)
    redirect_to exchange_path(exchange.code)
  end

  def exchange
    @exchange ||= Exchange.find_by!(code: params[:exchange_id])
  end

  def show
    not_found if market.nil?
    render :show
  end

  validates :update do
    boolean :subscribed, require: true, strong: true, description: 'Flag indicated whether this is subscribed'
  end
  def update
    market.update_attributes(update_params)
    market.save!
    render :show
  end

  private

  def market
    @market ||= Market.where('id = ? or (exchange_id = ? and code = ?)', params[:id].to_i, exchange.id.to_i, params[:id]).first
  end

  def exchange
    @exchange ||= Exchange.where('id = ? or code = ?', params[:exchange_id].to_i, params[:exchange_id]).first
  end

  def update_params
    params = permitted_params
    params
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  validates :create do
    string :exchange_id, required: true, strong: true
    string :market_id, required: true, strong: true
    string :time_in_force, required: true, strong: true, only: Order.time_in_forces.keys
    string :side, required: true, strong: true, only: Order.sides.keys
    string :price_type, required: true, strong: true, only: Order.price_types.keys
    float :price, required: true, strong: true
    float :quantity, required: true, strong: true
  end
  def create
    @order = Order.create(create_params)
    render json: @order, status: :created
  end
  
  private

  def create_params
    params = permitted_params
    params[:market_id] = market.id
    params.delete(:exchange_id)
    params
  end

  def market
    @market ||= Market.where('id = ? or (exchange_id = ? and code = ?)', params[:market_id].to_i, exchange&.id.to_i, params[:market_id]).first
  end

  def exchange
    @exchange ||= Exchange.where('id = ? or code = ?', params[:exchange_id].to_i, params[:exchange_id]).first
  end
end

app/controllers/root_controller.rb
# frozen_string_literal: true

class RootController < ApplicationController
  def index
    @markets = Market.includes(:exchange).where(subscribed: true)
    @api_key = ENV['BLUEGIANT_COINIGY_API_KEY']
    @api_secret = ENV['BLUEGIANT_COINIGY_API_SECRET']
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/root_helper.rb
# frozen_string_literal: true

module RootHelper
end

app/views/exchanges/index.html.slim
.container
  =form_tag(exchanges_path, method: :post) do
    input(type="submit" value="Refresh")
  table.table
    - @exchanges.each do |exchange|
      tr.bg-exchange
        td.bg-exchange-name() #{exchange.name}
        td.bg-exchange-code()
          a(href=exchange_path(exchange.code)) #{exchange.code}

app/views/exchanges/show.html.slim
javascript:
  $pageData = {
    markets: #{{@exchange.markets.to_json}}
  };
.container(ng-controller="ExchangesController" ng-init="init()")
  p
    a(href=exchanges_path) All Exchanges

  ul
    li Code: #{@exchange.code}
    li Name: #{@exchange.name}

  =form_tag(exchange_markets_path(@exchange.code), method: :post)
    input(type="submit" value="Refresh")

  Markets
  table.table
    tr.bg-market(ng-repeat="market in markets" ng-class="{'enabled': market.subscribed}" data-id="{{market.id}}")
      td.bg-market-code() {{market.code}}
      td.bg-market-subscription
        button(ng-click="toggleSubscription(market)") {{market.subscribed ? 'Disable' : 'Enable'}}

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    title BlueGiant
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
  body.nav-md(ng-app="BlueGiantApp" ng-controller="MainController" ng-init="init()")
    header
      nav.navbar.navbar-default.navbar-static-top.navbar-inverse
        .container-fluid
          .navbar-header
            button.navbar-toggle.collapsed(type="button" data-toggle="collapse" data-target="#bg-navbar" aria-expandanded="false")
              span.sr-only Toggle navigation
              span.icon-bar
              span.icon-bar
              span.icon-bar
          a.navbar-brand(href=root_path) BlueGiant
          .collapse.navbar-collapse#bg-navbar
            ul.nav.navbar-nav
              li
                a(href=exchanges_path)
                  | Exchanges <span class="sr-only">(current)</span>
    = yield

app/views/root/index.html.slim
javascript:
  var $pageData = {
    markets: #{{@markets.to_json(include: :exchange)}}
  };
.container(ng-controller="RootController" ng-init="init()" style="width: 100%;")
  .row
    .col-md-9
      .panel(ng-class="{'panel-danger':socketStatusIs(ERROR),
                        'panel-warning':socketStatusIs(CONNECTING),
                        'panel-success':socketStatusIs(CONNECTED)}")
        .panel-heading.dark(ng-switch="socketStatus")
          .row
            .col-md-9(style="font-size: 16pt;") Market Monitor
            .col-md-3
              select.form-control(
                ng-model="currencyPair"
                ng-options="pair for pair in MarketData.currencyPairs"
                ng-change="onCurrencyPairChange()")
                option(value="") -- Choose a currency pair --
        table.table.bg-blotter(ng-if="currencyPair")
          tr
            td.sortable(ng-click="changeOrder('id')"
                        ng-class="{'ordered':(blotterOrderKey=='id'),'reversed':blotterReversed}")
              | Currency 
            td.sortable(ng-click="changeOrder('bid_exchange')"
                        ng-class="{'ordered':(blotterOrderKey=='bid_exchange'),'reversed':blotterReversed}")
              | Bid Exch
            td.sortable(ng-click="changeOrder('ask_exchange')"
                        ng-class="{'ordered':(blotterOrderKey=='ask_exchange'),'reversed':blotterReversed}")
              | Ask Exch
            td.sortable.bg-number(ng-click="changeOrder('spread_bp')"
                                  ng-class="{'ordered':(blotterOrderKey=='spread_bp'),'reversed':blotterReversed}")
              | Spread (bps)
            td.sortable.bg-number(ng-click="changeOrder('spread')"
                                  ng-class="{'ordered':(blotterOrderKey=='spread'),'reversed':blotterReversed}")
              | Spread 
            td.bg-number Bid Price ({{currencyPair.split('/')[1]}})
            td.bg-number Ask Price ({{currencyPair.split('/')[1]}})
            td.bg-number Mid Price ({{currencyPair.split('/')[1]}})
          tr(ng-repeat="v in MarketData.blotters[currencyPair] | filter:{id:currencyPair} | orderBy:blotterOrderKey:blotterReversed | limitTo:20 track by v.id"
                 ng-class="{'highlight':(selectedPairId == v.id)}" data-key="{{v.id}}"
                 ng-click="selectPair(v.id)")
            td.col-md-2() {{$index + 1}} {{v.id}}
            td.col-md-1
              a(href="{{exchangeUrl(v.bid_exchange)}}" target="_blank") {{v.bid_exchange}}
            td.col-md-1
              a(href="{{exchangeUrl(v.ask_exchange)}}" target="_blank") {{v.ask_exchange}}
            td.col-md-1.bg-number.swap-animation(ng-animate-swap="v.spread_bp") {{v.spread_bp | number:8}}
            td.col-md-1.bg-number.swap-animation(ng-animate-swap="v.spread") {{v.spread | number:8}}
            td.col-md-2.bg-number.swap-animation(ng-animate-swap="v.bid_hi_price") {{v.bid_hi_price | number:8}}
            td.col-md-2.bg-number.swap-animation(ng-animate-swap="v.ask_lo_price") {{v.ask_lo_price | number:8}}
            td.col-md-2.bg-number.swap-animation(ng-animate-swap="v.mid_price") {{v.mid_price | number:8}}
        .panel-body(ng-if="!currencyPair")
          | Choose a currency pair ({{MarketData.currencyPairs.length}})
          ul
            li(ng-repeat="v in MarketData.currencyPairs")
              a(ng-click="changeCurrencyPair(v)" href="#") {{v}}
    .col-md-3(ng-if="selectedPairId")
      .panel
        .panel-heading.dark
          | Orders ({{selectedPairId}})
        .row
          .col-md-6
            table.table.bg-blotter
              tr
                th Price
                th Quantity
              tr(ng-repeat="bid in bids | orderBy:'-price' track by $index")
                td.bg-number() {{bid.price | number:8}}
                td.bg-number() {{bid.quantity | number:8}}
          .col-md-6
            table.table.bg-blotter
              tr
                th Price
                th Quantity
              tr(ng-repeat="ask in asks | orderBy:'price' track by $index")
                td.bg-number() {{ask.price | number:8}}
                td.bg-number() {{ask.quantity | number:8}}